import type { NextPage } from "next"
import Head from "next/head"
import { useContext } from "react"
import styled from "styled-components"

// Hook
import { UserInput } from "../hooks/UserInputContext"

const Home: NextPage = () => {
  const { userInput, setUserInput } = useContext(UserInput)

  return (
    <>
      <Head>
        <title>Casio Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <InputZone>
          <input type="text" placeholder="Title" />
          <textarea rows={15} cols={30} value={userInput} onChange={(e) => setUserInput(e.target.value)} placeholder="Enter text here"></textarea>
        </InputZone>
      </Main>
    </>
  )
}

const Main = styled.main`
  display: flex;
`

const InputZone = styled.section`
  display: flex;
  flex-direction: column;
`

export default Home
