import type { NextPage } from "next"
import { useState, useEffect } from "react"
import Head from "next/head"
import { TextConverterToCasio } from "../lib/textConverter"

const Home: NextPage = () => {
  const [userInput, setUserInput] = useState<string>("")
  const [loading, setLoading] = useState<boolean>(false)

  // blabla

  const startConversion = () => {
    setLoading(true)
    TextConverterToCasio(userInput)
    setLoading(false)
  }

  return (
    <div>
      <Head>
        <title>Casio Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {loading && <p>LOADING</p>}
        <textarea rows={15} cols={30} value={userInput} onChange={(e) => setUserInput(e.target.value)} name="userInputArea"></textarea>
        <button onClick={startConversion}>Click</button>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
